### ISSUE TITLE
Not sure if bug or I am misconfiguring something

### ISSUE THREAD

**Issue by Vidyut** [optimalisatie/above-the-fold-optimization#63]
This is happening
![delete](https://user-images.githubusercontent.com/697822/29784863-35dcc998-8c43-11e7-8c31-19bab1fb8490.png)
 
The unsecure url aamjanata.com/1e6e3e3e-b619-4815-af91-14000c3a7c28 in the screenshot is not present in the page source, so I imagine it is coming from the service worker (I could be wrong. I don't really understand how all this works - just a copy-paste hacker)

Also manifest contains service worker, but lighthouse no longer seems to see it, even though the service worker is prompting to allow notifications on the page being assessed.

**Comment by VidyutK** [comment]
Right now I'm trying to use the html5 web worker to load javascript + the PWA (without them and using my old PWA setup, I'm getting green all through, so this is experimenting to add these features - strictly)

**Comment by VidyutK** [comment]
Update: The issue seems to be with how the manifest gets saved. It is adding unnecessary backslashes to the code.

![delete](https://user-images.githubusercontent.com/697822/29785296-a83a10e4-8c44-11e7-848a-0a6172714daf.png)

Also the service worker doesn't seem to be registering the start page (I have selected it in the settings)

[Don't test my site without warning me, I'm switching back to my regular PWA when not trying to get the PWA from your plugin to work - so it may be all green, but it is the old PWA]

**Comment by HansVanEijsden** [comment]
Hi @VidyutK (nice to see you here, I remember you from the mod_pagespeed/ngx_pagespeed group!), do you have the latest version of the plugin? The problem with registering the service worker has been fixed some hours ago.
And as far as I know, the back slashes are needed because of escaping the forward slashes, correct me if I'm wrong. 😉

**Comment by VidyutK** [comment]
Oh Hi!!

That is strange. It still isn't saving the start page for my site.

The backslashes are landing up in the actual json file. Taking them out manually gets the manifest.json recognized again (or browser says there isn't one). Not sure what is going on. My normal manifest didn't have them either.

**Comment by optimalisatie** [comment]
The backslash issue has been solved in `v2.8.20`. The start_url preloading has been moved to the service worker installation.

We are still investigating it.

**Comment by Vidyut** [comment]
I got two updates back to back. Neither have solved the start page issue.

Appreciate the work you guys are doing.
