### ISSUE TITLE
DOMException on css-extract-widget.js if using google-fonts-Tag

### ISSUE THREAD

**Issue by xstable** [optimalisatie/above-the-fold-optimization#94]
I have checked a Page with your above-the-fold-optimization/admin/js/css-extract-widget.js file, which has this google-font -Tag in Source-Code: 

`<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Merienda+One%7C&amp;subset=latin" media="all">`

As result, I got an error like this: 
```
Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at getMatchedCSSRules (<anonymous>:309:42)
    at parseTree (<anonymous>:69:35)
    at new CSSCriticalPath (<anonymous>:161:9)
    at window.extractCriticalCSS (<anonymous>:522:18)
    at <anonymous>:1:8
```
If I remove this "google-font"-TAG  in the Browser-Console, script works like a charm.

**Comment by optimalisatie** [comment]
Hi xstable,

Thank you for your bug report! 

We have published a new CSS Optimization plugin with an improved critical CSS widget. The Page Speed Optimization plugin will soon be replaced by a combination of optimization modules. The currently missing module is PWA Optimization, the other modules are already available on Github.

https://github.com/o10n-x/wordpress-css-optimization

The Critical CSS widget can also be used standalone on any website.

Could you please try the new widget and provide information about your browser (name and version)?

https://github.com/o10n-x/critical-css-widget

You can instantly export critical CSS by pasting the following code in the browser console:

```javascript
(function(d,c,s) {s=d.createElement('script');s.async=true;s.onload=c;s.src='https://cdn.rawgit.com/o10n-x/critical-css-widget/master/critical-css-widget.min.js';d.head.appendChild(s);})(document,function() {
   // critical css file download
   o10n.extract();
});
```

**Comment by xstable** [comment]
Hi, still not work with executing your posted code in browser console. Give it a try and have a look at https://www.suther.de, same error as described in my first post.

**Comment by optimalisatie** [comment]
The widget works in Chrome 62. The widget is based on a concept by Paul Kinlan, head of Chrome webdeveloper relations team. 

https://gist.github.com/PaulKinlan/6284142

The original snippet uses a Chrome innovation called getMatchedCSSRules which is deprecated and will be removed in Chrome 63. The Critical CSS Widget is made cross browser using a polyfill for `getMatchedCSSRules`. It may be that your browser does not support it.

![image](https://user-images.githubusercontent.com/8843669/36542878-66d97b56-17e2-11e8-91c1-a89c3273e4ea.png)
